config/routes.rb
ColorMe::Application.routes.draw do
  
  resources :users
  resources :comments 
  resources :folders
  resources :videos
  resources :owns
  resources :comments
  resources :watches
  resources :sessions, only:[:new,:create,:destroy]#to have track of sessions

  root to: 'pages#home'
  
  match '/contact', to: 'pages#contact'
  match '/about', to: 'pages#about'
  match '/help', to: 'pages#help'
  
  match '/state', to: 'owns#state'
  match '/signup',  to: 'users#new'
  match '/signin', to: 'sessions#new' #imposto il metodo new per il session controller
  match '/signout', to: 'sessions#destroy', via: :delete #significa che la distruzione della sessione dovrebbe essere invocata da un http delete request
  
  match '/newfolder', to: 'folders#new'
  match '/newvideo', to: 'videos#new'
  match '/videosfolder', to: 'pages#visualizzaVideo'
  match '/emotion', to: 'comments#emotion'  
  match '/voto', to: 'watches#pippo'
  match '/aggiornamento', to: 'comments#aggiornamento'
  match '/commentiAggiornamento', to: 'comments#commentiAggiornamento'
  match '/utenti', to: 'users#viewusers'

end

app/views/pages/about.html.erb
<% provide(:title, 'Chi Siamo') %>
<div class="center hero-unit">
	<h1>Sviluppatori sito web</h1>
	</br>
	<h4>Sviluppo logica lato server</h4>
	<p>Giacomo Delfini dgiac85@gmail.com</p>
	<h4>Sviluppo logica lato client</h4>
	<p>Fierro Silvia s190718@studenti.polito.it</p>
</div>

app/views/pages/contact.html.erb
<% provide(:title, 'Contattaci') %>

<div class="center hero-unit">
	<h1>Contatta gli sviluppatori del sito web</h1>
	<p>Fierro Silvia s190718@studenti.polito.it</p>
	<p>Giacomo Delfini dgiac85@gmail.com</p>
</div>
 

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>
<div class="center hero-unit">
	<h1>Help!</h1>
	
</div>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %> 
<% if signed_in?%>
		<div class="row-fluid">
			<%=render 'layouts/sottoheader'%>			
		</div>
	     <div class="row-fluid" style="margin-top: 30px;">
	      	<div class="span3">
	         	<%= render 'layouts/elencocartelle'%>
	    	</div>
	    	<div class="span8">
	    		<%= render 'layouts/contenutoHome'%>	
	      	</div>
	      </div>
	
<% else%>	
	<div class="center" style=" margin:25px;padding-top: 0px; padding-bottom: 0px;">
	<h1>Benvenuto in colorme!</h1>
	<h2>Dai un colore alle tue conoscenze informatiche!</h2>
	</br>
	<div class="row-fluid">
		<div class="span12" style="margin:auto">
			<div class="row-fluid">				
					<%= image_tag "logo_computer.png" , :size=>"461x346" %>							
			</div>
			<div class="row">		
				<%= link_to "Sono già iscritto e posso vedere i video tutorial", signin_path , class: "styled-button-11" %>
				<%= link_to "Sono nuovo e voglio iscirvermi a colorme", signup_path , class: "styled-button-11" %>
			</div>	
			</div>
		</div>
	</div>
<% end%>

app/views/pages/visualizzaVideo.html.erb
<% provide(:title, 'i video') %>
<div class="row-fluid">
		<%=render 'layouts/sottoheader'%>
</div>
 <div class="row-fluid">
  	<div class="span3">
  		<a href="<%=root_path%>" class="btn" style="color: black;">Torna alle tue cartelle</a>
     	<%= render 'layouts/utenticartella'%>
	</div>
	<div class="span8">
		<%= render 'layouts/contenutoVideo'%>	
  	</div>
</div>