config/routes.rb
ColorMe::Application.routes.draw do
  
  resources :users
  resources :comments 
  resources :folders
  resources :videos
  resources :owns
  resources :comments
  resources :watches
  resources :sessions, only:[:new,:create,:destroy]#to have track of sessions

  root to: 'pages#home'
  
  match '/contact', to: 'pages#contact'
  match '/about', to: 'pages#about'
  match '/help', to: 'pages#help'
  
  match '/state', to: 'owns#state'
  match '/signup',  to: 'users#new'
  match '/signin', to: 'sessions#new' #imposto il metodo new per il session controller
  match '/signout', to: 'sessions#destroy', via: :delete #significa che la distruzione della sessione dovrebbe essere invocata da un http delete request
  
  match '/newfolder', to: 'folders#new'
  match '/newvideo', to: 'videos#new'
  match '/videosfolder', to: 'pages#visualizzaVideo'
  match '/emotion', to: 'comments#emotion'  
  match '/voto', to: 'watches#pippo'
  match '/aggiornamento', to: 'comments#aggiornamento'
  match '/commentiAggiornamento', to: 'comments#commentiAggiornamento'
  match '/utenti', to: 'users#viewusers'

end

app/views/layouts/_contenutoHome.html.erb
<div class="testo_content">
	<div class="row" id="uno" style="display: none">
		<div class="span1"><img width="40" height="40" src="http://upload.wikimedia.org/wikipedia/commons/8/8e/1leftarrow.png">
		</div>
		<div class="span1">
			<p>
				1
			</p>
		</div>
		<div class="span6" >
			<div onmouseenter="fammivedere('uno')" onmouseleave="fammivedere('uno')" style="cursor: pointer" >
				<p>
					Clicca sul colore che più ti rappresenta per ogni argomento
				</p>
			</div>
		</div>
<!-- 		<div class="span1" onmouseenter="fammivedere('uno')" style="cursor: pointer"><i>Cosa vuol dire?</i></div> -->
	</div>

	<div class="row" id="unoN" style="display: none; " >
		<div class="span2">
			<p></p>
		</div>
		<div class="span2">
			<%= button_tag "",  :class=>"btn btn-danger"%><h5>Sei un utente poco esperto.</h5>
		</div>
		<div class="span2">
			<%= button_tag "",  :class=>"btn btn-warning"%><h5>Sei un utente informato, ma poco sicuro.</h5>
		</div>
		<div class="span2">
			<%= button_tag "",  :class=>"btn btn-success"%><h5>Sei un utente esperto, vuoi condividere quello che sai.</h5>
		</div>
	</div>
	
	</br>
	<div class="row" id="due" style="display: none">
		<div class="span1"><img width="40" height="40" src="http://upload.wikimedia.org/wikipedia/commons/8/8e/1leftarrow.png">
		</div>
		<div class="span1">
			<p>
				2
			</p>
		</div>
		<div class="span6" >
			<div onmouseenter="fammivedere('due')" onmouseleave="fammivedere('due')" style="cursor: pointer" >
				<p>
					Clicca sul nome della cartella per iniziare
				</p>
			</div>
			
		</div>
<!-- 		<div class="span1" onclick="fammivedere('due')" style="cursor: pointer"><i>Cosa vuol dire?</i></div> -->
	</div>
	<div class="row" id="dueN" style="display: none">
		<div class="span2">
			<p></p>
		</div>
		<div class="span6">
			<%= image_tag 'imm_click.png', :class => "style_image"%>
		</div>
		
	</div>
	</br>
	<div class="row" id="tre" style="display: none">

		<div class="span1"><img width="40" height="40" src="http://upload.wikimedia.org/wikipedia/commons/8/8e/1leftarrow.png">
		</div>
		<div class="span1">
			<p>
				3
			</p>
		</div>
		<div class="span6">
			<div onmouseenter="fammivedere('tre')" onmouseleave="fammivedere('tre')" style="cursor: pointer" >
				<p>
					Guarda il video tutorial, confronta i pareri con gli amici
				</p>
			</div>
		</div>
<!-- 		<div class="span1" ><i>Cosa vuol dire?</i></div> -->
	</div>
	<div class="row" id="treN" style="display: none">
		<div class="span2"><p></p></div>
		<div class="span6">
			<%= image_tag 'imm_comments.png', :class => "style_image"%>
		</div>
	</div>
	
	</br>
	<div class="row" id="quattro" style="display: none">
		<div class="span1"><img width="40" height="40" src="http://upload.wikimedia.org/wikipedia/commons/8/8e/1leftarrow.png">
		</div>
		<div class="span1">
			<p>
				4
			</p>
		</div>
		<div class="span6">
			<div onmouseenter="fammivedere('quattro')" onmouseleave="fammivedere('quattro')" style="cursor: pointer" >
				<p>
					Autovaluta la tua conoscenza e aumenta di livello!
				</p>
			</div>
		</div>
		
	</div>
	<div class="row" id="quattroN" style="display: none">
		<div class="span2">
			<p></p>
		</div>
		<div class="span2">
			<%= image_tag("logo_computer_red.png", :size => "60x60" )%><h5>Non ho ancora capito l argomento. <strong>Guadagni un punto per la difficoltà video</strong></h5>
		</div>
		<div class="span2">
			<%= image_tag("logo_computer_giallo.png", :size => "60x60" )%><h5>Sono insicuro, voglio rivedere delle cose. <strong>Guadagni due punti per la difficoltà video </strong></h5>
		</div>
		<div class="span2">
			<%= image_tag("logo_computer_verde.png", :size => "60x60" )%><h5>Tutto chiarissimo! <strong>Guadagni tre punti per la difficoltà video </strong></h5>
		</div>
	</div>
	</br>
</div>

app/views/layouts/_contenutoVideo.html.erb
<div>
	<% if Video.count == 0%>
		<h1>Ooops...non ci sono ancora video per questo argomento...<br/>...magari ripassa in un secondo momento!</h1>
	<%else%>
	<table class="table table-condensed">
		<thead>
			<tr>
				<th><h6>Titolo</h6></th>
				<th><h6>Autore</h6></th>
				<th><h6>Descrizione</h6></th>
				<th><h6>Grado di difficoltà</h6></th>
				<th><h6>Vai al video!</h6></th>
			</tr>
		</thead>
		<%= Video.find_each do |video|%>
		<%if video.folder.id == @b.to_i %>
		<tr>
			<td>
				<h4><%= video.title %></h4>
			</td>
			<td>
			
				<%= video.user.name %>
			</td>
			<td >
			
				<%= video.description %>
			</td>
			<td>
				
				<p id="tl" rel="tooltip" title="Più segui un corso difficile più aumenti di punteggio!" style="cursor: pointer"><%= video.valuevideo%></p>
			</td>
			<td> <%= link_to "Vai al video", comments_path(:url=>video.url, :video_id=>video.id, :folder_id=>video.folder_id), class:"btn"   %> </td>
			</h6>
		</tr>
		<%end%>
	<%end%>
	</table>
<%end%>	
</div>

app/views/layouts/_elencocartelle.html.erb
<% if !current_user.admin?%>
<div class="well sidebar-nav">
	<ul class="nav nav-list">
		<% if current_page?(users_path)%>

		<li class="nav-header">
			Clicca sui nomi degli argomenti e vedi gli utenti che vi partecipano!
		</li>
		<li >
			<%= Folder.find_each do |folder|%>
			<h3><%= link_to folder.namefolder, utenti_path(:folder_id=>folder.id), :method=> :post, :remote=> true %></h3>
			<%end%>
		</li>
	</ul>
</div>
<%else%>
<li class="nav-header">
	Gli argomenti che hai scelto di seguire!
</li>
<li>
	<%= link_to "Aggiungo o Rimuovo argomenti", edit_own_path(current_user), class:"btn"%>
</li>
<%= Own.find_each do |own|%>
<%if own.user_id==current_user.id %>
<li style=" box-shadow: 10px 10px 5px #888; margin-top: 20px;  border-radius:10px;">

	<% if own.state==0%>
	<h3 id="<%= own.folder.id%>" name="<%= own.folder.id%>" ><%= own.folder.namefolder%></h3>

	<h3><%= link_to  own.folder.namefolder, videosfolder_path(:folder_id=> own.folder.id), :name=>own.folder.id, :hidden=> true %></h3>
	<div id="<%= own.folder.id%>">

		<%= link_to "ROSSO", state_path(:id=>"1", :folder_id=> own.folder.id),  :id=> own.folder.id, :name=>"rosso",   :onclick=>"nascondi(this.id, this.name)",  :method=> :post,   :remote=> true , :class=> "btn btn-danger",:rel=>"popover", :data=>{:content => 'Non sei esperto in questo argomento. Vuoi imparare!', :title=>"Utente rosso"} %>
		<%= link_to "GIALLO", state_path(:id=>"2", :folder_id=> own.folder.id), :id=> own.folder.id, :name=>"giallo", :onclick=>"nascondi(this.id, this.name)", :method=> :post,   :remote=> true, :class=> "btn btn-warning"  , :rel=>"popover",:data=>{:content => 'Sai l\'argomento in maniera sommaria. Vuoi impararlo meglio!', :title=>"Utente giallo"} %>
		<%= link_to "VERDE", state_path(:id=>"3", :folder_id=> own.folder.id),:id=> own.folder.id, :name=>"verde", :onclick=>"nascondi(this.id, this.name)", :method=> :post,   :remote=> true , :class=> "btn btn-success" , :rel=>"popover",:data=>{:content => 'Sei molto esperto! Vuoi dare consigli altri altri utenti.', :title=>"Utente Verde"} %>
	</div>
	<%end%>

	<% if own.state==1 %>
	<h3><%= link_to own.folder.namefolder, videosfolder_path(:folder_id=> own.folder.id)%></h3>
	<%= image_tag("logo_computer_red.png", :size => "60x60" )%>

	<%end%>

	<% if own.state==2 %>
	<h3 ><%= link_to own.folder.namefolder, videosfolder_path(:folder_id=> own.folder.id)%></h3>
	<%= image_tag("logo_computer_giallo.png", :size => "60x60")%>
	<%end%>

	<% if own.state==3 %>
	<h3><%= link_to own.folder.namefolder, videosfolder_path(:folder_id=> own.folder.id) %></h3>
	<%= image_tag("logo_computer_verde.png", :size => "60x60")%>
	<%end%>

	<%end%>

</li>
<%end%>
</ul>
</div>
<%end%>

<%else%>

<div class="well sidebar-nav">
	<ul class="nav nav-list">

		<% if current_page?(users_path)%>

		<!-- <li class="nav-header">
		Clicca sui nomi degli argomenti e vedi gli utenti che vi partecipano!
		</li> -->
		<li>
			<%= Folder.find_each do |folder|%>
			<h3><%= link_to folder.namefolder, utenti_path(:folder_id=>folder.id), :method=> :post, :remote=> true %></h3>
			<%end%>
		</li>
	</ul>
</div>
<%else%>
<li class="nav-header">
	Le cartelle presenti su colorme
</li>
<%= Folder.find_each do |folder|%>
<h3><%= link_to folder.namefolder, videosfolder_path(:folder_id=> folder.id), :name=>folder.id %></h3>

<%end%>
</ul>
</div>
<%end%>

<%end%>

app/views/layouts/_footer.html.erb
<hr class="hrstyle" style="margin-bottom:10px; height:5px; background-color: #63343a" />
<div class="row-fluid" style="background-color: #fcedd6;margin-top:10px;">
  	<div class="span6">
  	  <h6>
	<%= link_to (image_tag "bitbucket.jpg",  :size => "15x15"),  "https://bitbucket.org/Tofi/colorme_site" %>
		<a href="https://bitbucket.org/Tofi/colorme_site">Colorme 2012 | Ingegneria del Cinema e dei Mezzi di Comunicazione | Politecnico di Torino </a> 
	  </h6>	
	</div>
	<div dlass="span 6" style="float:right">
		<%= link_to (image_tag "rails.png",  :size => "33x42"),  "http://ruby.railstutorial.org/" %>
	</div>	
</div>



app/views/layouts/_formComment.html.erb
<p>Qui ci va il form</p>
<p><%=params[:video_id]%></p>
<%= link_to "vai", commento_path(:id=>"commento", :video_id=>params[:video_id]), class:"button", :onclick=>"addParam(this)", :method=> :post,  :remote=> true %>
<%=form_for(current_user.comments.create(:user_id=>current_user.id, :video_id=>params[:video_id], :text=> :text ), remote: true) do |f|%>
<%= f.text_area :text%> 
<%= f.submit :import!%>

app/views/layouts/_header.html.erb
<!-- Navigation bar -->

<div class="top">
	<div id="infosite">
		<h1 >colorme</h1>
	</div>
	<div style="float:right;margin-top: 10px">
		<%= render 'layouts/infosite' %>
	</div>
</div>
<header class="navbar navbar-fixed-top" style="height:10px">
	<div class="navbar-inner">
		<div class="container">
			
			<nav>
				<%if signed_in? %>
				<ul class="nav pull-right">

					<li>

						<%= link_to "Esci da colorme", signout_path, method: "delete" %>

					</li>
				</ul>
				<%end%>
				<ul class="nav pull-&#x2190;">

					<% if signed_in? %>
					<li>
						<%= link_to "Pagina Principale", root_path %>
					</li>
					<li>
						<%= link_to "Gli altri iscritti", users_path(:folder_id => "0") %>
					</li>

					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Il mio Profilo <b class="caret"></b> </a>
						<ul class="dropdown-menu">
							<!-- <li><%= link_to "Il mio profilo sul sito", current_user %></li> -->
							<!-- <li class="divider"></li> -->
							<% if current_user.admin? %>
							<li>
								<%= link_to "Crea una cartella", newfolder_path %>
							</li>
							<li>
								<%= link_to "Le cartelle che hai creato","#" %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to "Aggiungi video ad una cartella", newvideo_path %>
							</li>							
							<% end%>
							<li>
								<%= link_to "I miei dati", user_path(current_user) %>
							</li>
							<li>
								<%= link_to "Aggiorno i miei dati", edit_user_path(current_user) %>
							</li>
							<!-- <li class="divider"></li> -->
						</ul>

					</li>
					<% if !current_user.admin?%>
					<li>
						<%= link_to "Aggiungo e rimuovo argomenti", edit_own_path(current_user)%>
					</li>
					<%end%>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_infosite.html.erb
<blockquote class="pull-right">
	<h6>
		<% if !signed_in?%>
		<%= link_to " Pagina Principale  ",   root_path %> |
		<%end%>				
		
		<%= link_to " La squadra di colorme  ",   about_path %> |
      	<a href="http://bit.ly/lingambmult">LAM 2012</a> 			
	</h6>
</blockquote>	   
  		  

app/views/layouts/_posts.html.erb
<p><%= params[:video_id] %></p>
<%= Comment.find_each do |comment|  %>
	<% if comment.video_id == params[:video_id]%>
<p><%=comment.text%></p>
<%end%>
<%end%>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sottoheader.html.erb
<% flash.each do |key, value| %>
<%= content_tag(:div, value, class: "alert") %>
<% end %>
<div class="span4" style="margin-bottom: 30px;>
<a href="<%= user_path(current_user) %>"><%= gravatar_for current_user, size: 52, :default=>'identicon' %></a>
<h1 style="text-align:left"><%= current_user.name %></h1>
<h4><%= current_user.email %></h4>
</div>
<%if current_page?(root_path)%>

<div class="span4">
<div class="row-fluid"><%= image_tag("up_arrow.png" )%></div>
<div class="testo_content"><p >Gestisci il tuo profilo!</p></div>

</div>
<%end%>

<!-- controllo sulla pagina -->
<% if current_page?(comments_path)%>
<div class="span4">

<span class="emozioni">
<div class="row-fluid">
<h4 >Comunica agli altri utenti il tuo stato d'animo!
</br>Sicuramente qualcuno saprà aiutarti!</h4>
</div>

<div class="row-fluid" style="padding-top: 10px; padding-bottom: 20px;">
<div class="span2">
<%= link_to ":)", { :controller => 'comments', :action => 'emotion', :emozione => "1" }, :id=>"1", :onclick=>"cambiaEmozione(this.id)",   class:"btn",:remote=> true, :rel=>"popover", :data=>{:content => 'questa emoticon ti permette di dire agli altri utenti che sei felice di quello che stai imparando!', :title=>"Felice"} %>
<span class="example" style="display: none"> PROVA PROVA</span>
</div>
<div class="span2">
<%= link_to ":(", { :controller => 'comments', :action => 'emotion', :emozione=> "2" },:id=>"2", :onclick=>"cambiaEmozione(this.id)", class:"btn",:remote=> true, :rel=>"popover", :data=>{:content => 'questa emoticon ti permette di dire agli altri utenti che sei triste! Magari qualcuno potrà darti una mano!', :title=>"Triste"} %>
</div>
<div class="span2">
<%= link_to ":@", { :controller => 'comments', :action => 'emotion',  :emozione => "3" }, :id=>"3",:onclick=>"cambiaEmozione(this.id)", class:"btn",:remote=> true, :rel=>"popover", :data=>{:content => 'questa emoticon ti permette di dire aglia altri utenti che sei arrabbiato. Non stai capendo qualcosa? Magari qualcuno può aiutarti subito!', :title=>"Arrabbiato"} %>
</div>
<div class="span2">
<%= link_to "-.-", { :controller => 'comments', :action => 'emotion',  :emozione => "4" }, :id=>"4",:onclick=>"cambiaEmozione(this.id)", class:"btn",:remote=> true, :rel=>"popover", :data=>{:content => 'questa emoticon ti permette facilmente di dire agli altri che sei annoiato. Magari qualcuno ha qualche video interessante da farti vedere!', :title=>"Annoiato"} %>
</div>
<div class="span4"><h5 id="emoz" style="display: none;"></h5></div>

</div>

</span>

</div>
<%end%> 

app/views/layouts/_utenticartella.html.erb
<div class="well sidebar-nav"> 		
  <ul class="nav nav-list">
  		
  		
  	<li class="nav-header">Gli altri utenti che imparano con te</li>
  	<%=  Own.find_each do |own|%>
  		<% if own.folder_id == @b.to_i %>
  			<%= User.find_each do |user| %>
  				<% if own.user_id == user.id && own.user_id != current_user.id %> 
  				<%= link_to user_path(user.id) do %>
  				<div class="row" style=" box-shadow: 10px 10px 5px #888; margin-top: 20px;  border-radius:10px;" >
  					<div class="span3">
  						<p><%=user.name%></p>
  						</div>
  						<div class="span3">
  						<%if own.state == 1 %>
  							<%= image_tag("logo_computer_red.png", :size => "80x80" )%>
  						<%end%>
  						<%if own.state == 3 %>
  							<%= image_tag("logo_computer_verde.png", :size => "80x80")%>
  						<%end%>
  						<%if own.state == 2 %>
  							<%= image_tag("logo_computer_giallo.png", :size => "80x80")%>
  						<%end%>  
  						
  						</div>
  						<div class="span3">
  						<div id="emozione">
  							<% if user.emotion == 1%>
  							<p>Allegro</p>
  							<%end%>
  							<% if user.emotion == 2%>
  							<p>Triste</p>
  							<%end%>
  							<% if user.emotion == 3%>
  							<p>Arrabbiato</p>
  							<%end%>
  							<% if user.emotion == 4%>
  							<p>Annoiato</p>
  							<%end%>
  						</div>	
  						</div>
  				</div> 					
  					<%end%>
  					
  					
  				<%end%>
  			<%end%>
  			
  			<%end%>
  	<%end%>
	  
	  
  </ul>
</div><!--/.well -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title><!-- Si richiama il metodo full_title presente nell'helper -->
  
  
  <%= stylesheet_link_tag "application", :media => "all" %>
  
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag  "rails.validations" %>  
 
  
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  
</head>
<body onload="showContent()" style="background-color: #fcedd6;">

			
		<%= render 'layouts/header' %>
		<!-- Main content -->
		
		<div class="container-fluid" style="margin-top: 33px; margin-bottom:0px;background-color: #fcedd6;">			
			<script type="text/javascript">
				document.write('<div id="loading"><h1>Attendere Prego... </h1><div><h1><%=image_tag src="ajax-loader1.gif"%></h1></div></div>');
			</script>			
			<div class="row-fluid" style="margin-top: 20px;">				
				<div class="span12">					
					<div id="content">
						<script type="text/javascript">
							//hide content							
							document.getElementById("content").style.display = 'none';							
						</script>			
						<%= yield %>	
					</div>
				</div>
			</div>
		</div>

        <%= render 'layouts/footer' %>
       


</body>
</html>